# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

# Main build stage.

jobs:

# Linux build, which publishes the main artifacts

- job: build_linux
  pool:
    vmImage: ubuntu-20.04

  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  # Build

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      jlpm install
    displayName: jlpm install

  # Create and stage our artifacts. (No reason not to do this ASAP -- these can
  # help debug build problems.)

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      jlpm pack
    displayName: jlpm pack

  - bash: |
      set -xeuo pipefail
      mkdir -p $ARTIFACT_STAGING/npm
      cp *.tgz $ARTIFACT_STAGING/npm
    displayName: Stage NPM package artifacts

  - task: PublishPipelineArtifact@0
    displayName: Publish NPM package artifacts
    inputs:
      artifactName: npm
      targetPath: $(Build.ArtifactStagingDirectory)/npm

  # Test

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      jlpm run test
    displayName: jlpm test


# MacOS - build/test but no artifacts

- job: build_macos
  pool:
    vmImage: macos-10.15
  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      jlpm install
    displayName: jlpm install

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      jlpm run test
    displayName: jlpm test


# Lint

- job: lint
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      jlpm install
    displayName: jlpm install

  - bash: |
      set -euo pipefail
      source activate-conda.sh
      conda activate build
      set -x
      jlpm run eslint:check
    displayName: jlpm eslint
