# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

trigger:
  branches:
    include:
    - master
    - rc

stages:
- stage: ApplyVersions
  jobs:
  - template: azure-apply-versions.yml

- stage: MainBuild
  jobs:
  - template: azure-main-build.yml

# Note: no CD activities (i.e. things that happen on updates to `master`)
- stage: Deploy
  condition: and(succeeded('MainBuild'), ne(variables['build.reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'rc'))
  jobs:
  - template: azure-deployment.yml
    parameters:
      isMainDev: ${{ ne(variables['Build.SourceBranchName'], 'rc') }}
      isRelease: ${{ eq(variables['Build.SourceBranchName'], 'rc') }}
