# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

# Main build stage.

parameters:
- name: 'zolaVersion'
  default: '0.10.1'
  type: string

jobs:

# Linux build, which publishes the main artifacts

- job: build_linux
  pool:
    vmImage: ubuntu-20.04

  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  # Build

  - bash: npm run build
    displayName: NPM build

  # Create and stage our panoply of artifacts. (No reason not to do this ASAP --
  # these can help debug build problems.)

  - bash: npm run pack
    displayName: NPM pack

  - bash: |
      set -xeuo pipefail
      mkdir -p $ARTIFACT_STAGING/npm
      cp */*.tgz $ARTIFACT_STAGING/npm
    displayName: Stage NPM package artifacts

  - task: PublishPipelineArtifact@0
    displayName: Publish NPM package artifacts
    inputs:
      artifactName: npm
      targetPath: $(Build.ArtifactStagingDirectory)/npm

  - task: CopyFiles@2
    displayName: Stage research-app artifacts
    inputs:
      sourceFolder: research-app/dist
      targetFolder: $(Build.ArtifactStagingDirectory)/research-app

  - task: PublishPipelineArtifact@0
    displayName: Publish research-app artifacts
    inputs:
      artifactName: research-app
      targetPath: $(Build.ArtifactStagingDirectory)/research-app

  # Test

  - bash: npm run test
    displayName: NPM test


# MacOS - build/test but no artifacts

- job: build_macos
  pool:
    vmImage: macos-10.15
  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  - bash: npm run build
    displayName: NPM build

  - bash: npm run test
    displayName: NPM test

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'engine/tests/results.xml'

# Lint

- job: lint
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: azure-job-setup.yml
    parameters:
      setupBuild: true

  - bash: npm run build
    displayName: NPM build

  - bash: npm run lint
    displayName: NPM lint

# Docs

# - job: docs
#   pool:
#     vmImage: ubuntu-20.04
#   steps:
#   - template: azure-job-setup.yml
#     parameters:
#       setupBuild: true
#
#   - bash: npm run build
#     displayName: NPM build
#
#   - script: npm run doc
#     displayName: NPM doc
#
#   - bash: |
#       set -xeuo pipefail
#       fn="zola-v${{ parameters.zolaVersion }}-x86_64-unknown-linux-gnu.tar.gz"
#       u="https://github.com/getzola/zola/releases/download/v${{ parameters.zolaVersion }}/$fn"
#       wget "$u"
#       tar xzf "$fn"
#       rm -rf "$fn"
#     displayName: Install Zola
#
#   - bash: |
#       set -xeuo pipefail
#       cd docs
#       ../zola check
#     displayName: Check Zola docs site
#
#   - bash: |
#       set -xeuo pipefail
#       cd docs
#       ../zola build -o $ARTIFACT_STAGING/docs
#     displayName: Zola docs build
#
#   - task: PublishPipelineArtifact@0
#     displayName: Publish docs artifacts
#     inputs:
#       artifactName: docs
#       targetPath: $(Build.ArtifactStagingDirectory)/docs
