base_url = "//docs.worldwidetelescope.org/research-kit/1/"
title = "WWT Research Kit Manual"
description = "The manual AAS WorldWide Telescope research tools."
theme = "wwtguide"

[extra]
github_base = "//github.com/WorldWideTelescope/wwt-research-kit"
google_analytics_id = "UA-107473046-3"
